services:
  db:
    image: postgres:16-alpine 
    container_name: postgres_realestate_db
    environment:
      POSTGRES_DB: realestatedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: